services:
  - type: web
    name: my-telebot-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT main:app"
    envVars:
      - key: PORT
        value: 5000
      - key: TOKEN
        value: 6782919923:AAGE4n20pIXTb21cXYAI-oH13K0si6usKEA
    pythonVersion: 3.8


