services:
  - name: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.8
    envVars:
      - key: PORT
        value: 5000
    plan: free

