services:
  - type: web
    name: my-telebot-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    pythonVersion: 3.8
    envVars:
      - key: PORT
        value: 5000
